name: app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  dio_http_cache: ^0.2.11
  badges: ^1.1.4
  cached_network_image: ^2.4.1
  get: ^3.22.2
  json_annotation: ^3.1.1
  flutter_secure_storage: ^3.3.5
  auto_size_text: ^2.1.0
  pull_to_refresh: ^1.6.3
  string_validator: ^0.1.4
  google_fonts: ^1.1.1
  line_icons: ^0.2.0
  flutter_snake_navigationbar: ^0.4.1+3
  icon_badge: ^0.0.1+5
  firebase_core:
  firebase_auth: ^0.18.4
  pin_code_fields:
  flutter_facebook_auth: ^1.0.2+1
  google_sign_in: ^4.5.6
  google_maps_flutter: ^1.0.6
  maps_toolkit: ^1.1.0+2
  firebase_dynamic_links: ^0.6.3
  firebase_crashlytics: ^0.2.4
  firebase_performance: ^0.4.3
  firebase_remote_config: ^0.4.3
  location: ^3.1.0
  pretty_dio_logger: ^1.1.1
  sqfentity:
  sqfentity_gen:
  flutter_markdown: ^0.5.1
  flutter_svg:
  catcher: ^0.3.23
  logging: ^0.11.4
  flare_flutter: ^2.0.6
  flutter_inappwebview: ^4.0.0+4
  json_to_store_menu:
    git:
      url: git://github.com/llegosv/json_to_store_menu.git



dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.1
  build_runner: ^1.10.7
  build_verify: ^1.1.1
  mockito: ^4.1.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/animations/
    - assets/images/
    - assets/icons/
