name: bookshop
description: Bookshop App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  badges: ^1.1.1
  cached_network_image: ^2.2.0+1
  flare_splash_screen: ^3.0.1
  font_awesome_flutter: ^8.8.1
  location: ^3.0.2
  mime: ^0.9.6+3
  flutter_bloc:
  equatable: ^1.2.0
  built_value: ^7.1.0
  built_collection: ^4.3.2
  dio:
  dio_http_cache:
  pull_to_refresh: ^1.6.0
  flutter_secure_storage:
  animate_do: ^1.7.2
  bubble_tab_indicator: ^0.1.4
  string_validator: ^0.1.4
  flare_flutter: ^2.0.5
  google_maps_flutter: ^0.5.28+1
  google_maps_webservice: ^0.0.17
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  firebase_messaging: ^6.0.16
  bubble: ^1.1.9+1
  modal_bottom_sheet: ^0.2.0+1
  timeline_node: ^0.1.0
  vibration: ^1.4.0
  permission_handler: ^5.0.1+1
  auto_size_text: ^2.1.0
  getwidget: ^1.1.0
  flutter_staggered_grid_view: ^0.3.0
  flutter_date_pickers: ^0.1.4
  flutter_form_bloc:
    git:
      url: git://github.com/c3rberuss/form_bloc.git
      path: packages/flutter_form_bloc

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  built_value_generator: ^7.1.0
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.7.5


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/animations/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700


flutter_icons:
  image_path_android: "assets/icons/logo2.png"
  image_path_ios: "assets/icons/logo2.png"
  android: true
  ios: true